stages:
- build_image
- deploy


.build: &build_tpl
  image: docker:latest
  services:
  - docker:dind

build_image:
  <<: *build_tpl
  stage: build_image
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-${CI_COMMIT_REF_SLUG}}
    --build-arg APP_NAME="\"${CI_PROJECT_TITLE}\""
    --build-arg GITLAB_USER=gitlab-ci-token
    --build-arg GITLAB_PASS=${CI_BUILD_TOKEN}
    ${CI_PROJECT_DIR}
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-${CI_COMMIT_REF_SLUG}}


deploy_image:
  <<: *build_tpl
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker compose pull
    - docker compose up -d
    - docker image prune -a -f