stages:
  - deploy
  - clear

.build: &build_tpl
  image: docker:latest
  services:
  - docker:dind


deploy:
  <<: *build_tpl
  stage: deploy
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-${CI_COMMIT_REF_SLUG}}
      --build-arg APP_NAME="\"${CI_PROJECT_TITLE}\""
      --build-arg GITLAB_USER=gitlab-ci-token
      --build-arg GITLAB_PASS=${CI_BUILD_TOKEN}
      ${CI_PROJECT_DIR}
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-${CI_COMMIT_REF_SLUG}}


clear:
  <<: *build_tpl
  stage: clear
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker compose pull
    - docker compose up -d
    - docker-compose app exec php artisan config:cache
    - docker image prune -a -f

