image: alpine:latest

pages:
  stage: deploy
  before_script:
  - apt update
  - apt install git
  script:
  - git  pull https://gitlab.com/pektiyaz/unec-new.git master
  artifacts:
    paths:
    - public
  only:
  - master