stages:
- build_image
- deploy
services:
- name: docker:dind
  entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

build_image: 
  stage: build_image
  script:
  - export DOCKER_HOST=tcp://127.0.0.1:2375 && docker build --pull -t ${CI_REGISTRY_IMAGE} .


deploy_image:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker compose pull
    - docker compose up -d
    - docker image prune -a -f