version: '3.5'

x-env: &env
    TZ: 'Asia/Baku'

x-backend: &backend
    image: https://gitlab.com/pektiyaz/unec-new:master
    restart: unless-stopped
    environment:
      <<: *env
      IMG_URL: 'http://212.193.54.230:5111'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'db.app.local'
      DB_DATABASE: 'unec_db'
      DB_USER: 'root'
      DB_PASSWORD: ''
      LOG_LEVEL: 'debug'
      APP_KEY: Kxi8y3P0iR892vq0fGksBhM36tNedF7A
    volumes:
    - /etc/localtime:/etc/localtime:ro
    links:
    - db:db.app.local
    depends_on:
    - db


services:
  db:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: unec_db
      MYSQL_USER: unec_user
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  scheduler:
    <<: *backend
    command: 'php artisan serve --host 0.0.0.0 --post 8000'
    healthcheck:
      disable: true

  api:
    <<: *backend
    ports:
    - 5111:3000/tcp
    depends_on:
    - db
    - scheduler
