version: '3'
services:
 database:
    image: mysql:latest
    container_name: "Mysql"
    restart: "no"
    volumes:
      - ./docker/database/init:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    networks:
      - laravel
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: unec_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    command: --default-authentication-plugin=mysql_native_password
  app:
    container_name: laravel
    command: './docker/run.sh'
  