version: '3'

services:
  app:
    build: ./web
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ../:/var/www/html
    ports:
      - 8000:80
    working_dir: /var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    command:
      - /bin/bash
      - -c
      - |
        mv docker/envdeploy ./.env
        chmod -R 777 storage
        chmod -R 777 bootstrap
        composer install
        php artisan config:cache
  

  
  

    
