version: '3'

services:
  app:
    build: ./web
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
    working_dir: /var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database:/var/lib/mysql
  
  composer:
    image: composer
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    command: composer install

    
